/*
 * This file re-exports the standard Grafana plugin webpack configuration
 * from .config/webpack/webpack.config.ts – generated by @grafana/create-plugin.
 *
 * To customise the build, edit .config/webpack/webpack.config.ts.
 */
import config from './.config/webpack/webpack.config';

export default config;
