/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-webpack-config
 */

import path from 'path';
import { fileURLToPath } from 'url';
import { readFileSync } from 'fs';
import webpack, { type Configuration } from 'webpack';
import CopyWebpackPlugin from 'copy-webpack-plugin';
// @ts-ignore – no types
import ReplaceInFileWebpackPlugin from 'replace-in-file-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
// @ts-ignore – no types
import LiveReloadPlugin from 'webpack-livereload-plugin';
import TerserPlugin from 'terser-webpack-plugin';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..', '..');
const SOURCE_DIR = 'src';
const DIST_DIR = 'dist';
const DIST = path.resolve(ROOT, DIST_DIR);

const pkg = JSON.parse(readFileSync(path.resolve(ROOT, 'package.json'), 'utf-8'));
const pluginJson = JSON.parse(readFileSync(path.resolve(ROOT, SOURCE_DIR, 'plugin.json'), 'utf-8'));

const cprcJson = JSON.parse(readFileSync(path.resolve(__dirname, '..', '.cprc.json'), 'utf-8'));
const cpVersion = cprcJson.versionChecked || 'unknown';

export type Env = {
  [key: string]: true | string | Env;
};

const config = async (env: Env): Promise<Configuration> => {
  const isProduction = Boolean(env.production);

  return {
    mode: isProduction ? 'production' : 'development',
    devtool: isProduction ? 'source-map' : 'eval-source-map',
    context: path.join(ROOT, SOURCE_DIR),
    entry: {
      module: './module.ts',
    },
    output: {
      path: DIST,
      filename: '[name].js',
      library: { type: 'amd' },
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: pluginJson.id,
      clean: true,
    },
    externals: [
      'react',
      'react-dom',
      '@grafana/data',
      '@grafana/ui',
      '@grafana/runtime',
      '@grafana/schema',
      'lodash',
      'emotion',
      '@emotion/css',
      '@emotion/react',
    ],
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
      modules: [path.resolve(ROOT, SOURCE_DIR), 'node_modules'],
    },
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'swc-loader',
            options: {
              jsc: {
                baseUrl: path.resolve(ROOT, SOURCE_DIR),
                parser: { syntax: 'typescript', tsx: true },
                transform: { react: { runtime: 'automatic' } },
                target: 'es2015',
              },
            },
          },
        },
      ],
    },
    optimization: {
      minimize: isProduction,
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            format: {
              comments: (_: unknown, { type, value }: { type: string; value: string }) =>
                type === 'comment2' && value.trim().startsWith('[create-plugin]'),
            },
            compress: {
              drop_console: ['log', 'info'],
            },
          },
        }),
      ],
    },
    plugins: [
      // Insert create-plugin version information into the bundle
      new webpack.BannerPlugin({
        banner: `/* [create-plugin] version: ${cpVersion} */\n/* [create-plugin] plugin: ${pluginJson.id}@${pkg.version} */`,
        raw: true,
        entryOnly: true,
      }),
      new CopyWebpackPlugin({
        patterns: [
          { from: 'plugin.json', to: 'plugin.json' },
          { from: 'img', to: 'img', noErrorOnMissing: true },
          { from: path.resolve(ROOT, 'README.md'), to: 'README.md', noErrorOnMissing: true },
          { from: path.resolve(ROOT, 'LICENSE'), to: '.', noErrorOnMissing: true },
          { from: path.resolve(ROOT, 'CHANGELOG.md'), to: 'CHANGELOG.md', noErrorOnMissing: true },
        ],
      }),
      new ForkTsCheckerWebpackPlugin({
        typescript: { configFile: path.resolve(ROOT, 'tsconfig.json') },
      }),
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          test: [/(^|\/)plugin\.json$/, /(^|\/)README\.md$/],
          rules: [
            { search: /\%VERSION\%/g, replace: pkg.version },
            { search: /\%TODAY\%/g, replace: new Date().toISOString().slice(0, 10) },
            { search: /\%PLUGIN_ID\%/g, replace: pluginJson.id },
          ],
        },
      ]),
      ...(!isProduction
        ? [new LiveReloadPlugin({ appendScriptTag: false })]
        : []),
    ],
  };
};

export default config;
